WJQ.OA.WebApp/Controllers/RoleInfoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WJQ.OA.BLL;
using WJQ.OA.IBLL;
using WJQ.OA.Model;
using static WJQ.OA.Common.EnumType;

namespace WJQ.OA.WebApp.Controllers
{
    public class RoleInfoController : BaseController
    {
        private IRoleInfoService RoleInfoService { get; set; }
        private IActionInfoService ActionInfoService { get; set; }
        // GET: RoleInfo
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult GetRoleInfoList()
        {
            int pageSize = Request["rows"] != null ? Convert.ToInt32(Request["rows"]) : 5;
            int pageIndex = Request["page"] != null ?Convert.ToInt32(Request["page"]) : 1;
            int totalCount = 0;
            short isDelete =(short)DeleteEnum.Normal;
            var RoleList = RoleInfoService.LoadPageEntities(pageIndex, pageSize, out totalCount, x => x.DelFlag == isDelete, x => x.ID, true);
            var temp = from u in RoleList
                       select new
                       {
                           ID=u.ID,
                           RoleName=u.RoleName,
                           Sort=u.Sort,
                           Remark=u.Remark,
                           SubTime=u.SubTime
                       };
            return Json(new { rows = temp, total = totalCount }, JsonRequestBehavior.AllowGet);
        }
        public ActionResult ShowAddInfo()
        {
            return View();
        }
        public ActionResult AddRoleInfo(RoleInfo role)
        {
            role.SubTime = DateTime.Now;
            role.ModifiedOn = "2018-09-09";
            role.DelFlag = 0;
            RoleInfoService.AddEntity(role);
            return Content("ok");
        }
        public ActionResult ShowRoleAction()
        {
            int id = int.Parse(Request["id"]);
            var roleInfo = RoleInfoService.LoadEntities(r => r.ID == id).FirstOrDefault();//获取要分配的权限的角色信息。
            ViewBag.RoleInfo = roleInfo;
            //获取所有的权限。
            short delFlag = (short)DeleteEnum.Normal;
            var actionInfoList = ActionInfoService.LoadEntities(a => a.DelFlag == delFlag).ToList();
            //要分配权限的角色以前有哪些权限。
            var actionIdList = (from a in roleInfo.ActionInfo
                                select a.ID).ToList();
            ViewBag.ActionInfoList = actionInfoList;
            ViewBag.ActionIdList = actionIdList;
            return View();
        }
        public ActionResult SetRoleAction()
        {
            int roleId = int.Parse(Request["roleId"]);//获取角色编号
            string[] allKeys = Request.Form.AllKeys;//获取所有表单元素name属性的值。
            List<int> list = new List<int>();
            foreach (string key in allKeys)
            {
                if (key.StartsWith("cba_"))
                {
                    string k = key.Replace("cba_", "");
                    list.Add(Convert.ToInt32(k));
                }
            }
            if (RoleInfoService.SetRoleActionInfo(roleId, list))
            {
                return Content("ok");
            }
            else
            {
                return Content("no");
            }
        }
    }
}

WJQ.OA.WebApp/Views/RoleInfo/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <link href="~/Content/default/easyui.css" rel="stylesheet" />
    <link href="~/Content/icon.css" rel="stylesheet" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/easyui-lang-zh_CN.js"></script>
    <script src="~/Scripts/jquery.easyui.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.js"></script>
    <script src="~/Scripts/datapattern.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script type="text/javascript">
        $(function () {
            $('#addDiv').css("display", "none");
            $("#setActionDiv").css("display", "none");
            loadData();
        });       
            
        function loadData(pars) {
            $('#tt').datagrid({
                url: '/RoleInfo/GetRoleInfoList',
                title: '用户角色表格',
                width: 700,
                height: 400,
                fitColumns: true, //列自适应
                nowrap: false,
                idField: 'ID',//主键列的列明
                loadMsg: '正在加载角色的信息...',
                pagination: true,//是否有分页
                singleSelect: false,//是否单行选择
                pageSize: 5,//页大小，一页多少条数据
                pageNumber: 1,//当前页，默认的
                pageList: [5, 10, 15],
                queryParams: pars,//往后台传递参数
                columns: [[
                    { field: 'ck', checkbox: true, align: 'left', width: 50 },
                    { field: 'ID', title: '编号', width: 80 },
                    { field: 'RoleName', title: '姓名', width: 120 },
                    { field: 'Sort', title: '标记', width: 120 },
                    { field: 'Remark', title: '备注', width: 120 },
                    {
                        field: 'SubTime', title: '注册时间', width: 80, align: 'right',
                        formatter: function (value, row, index) {
                            return (eval(value.replace(/\/Date\((\d+)\)\//gi, "new Date($1)"))).pattern("yyyy-M-d");
                        }
                    }
                ]],
                toolbar: [{
                    id: 'btnDelete',
                    text: '删除',
                    iconCls: 'icon-remove',
                    handler: function () {
                        deleteInfo();
                    }
                }, {
                    id: 'btnAdd',
                    text: '添加',
                    iconCls: 'icon-add',
                    handler: function () {
                        addInfo();
                    }
                }, {
                    id: 'btnEidt',
                    text: '编辑',
                    iconCls: 'icon-edit',
                    handler: function () {
                        showUpdateInfo();
                    }
                }, {
                    id: 'btnSetAction',
                    text: '为角色分配权限',
                    iconCls: 'icon-edit',
                    handler: function () {
                        showRoleAction();
                    }
                }],
            });
        }
        function showRoleAction() {
            //判断是否选择了一个角色.
            var rows = $('#tt').datagrid('getSelections');//获取所选择的行
            if (rows.length != 1) {
                $.messager.alert("提示", "请选择要分配权限的角色", "error");
                return;
            }
            //指定iframe的src.
            $("#setActionFrame").attr("src", "/RoleInfo/ShowRoleAction/?id=" + rows[0].ID);
            $("#setActionDiv").css("display", "block");
            $('#setActionDiv').dialog({
                title: '为角色分配权限数据',
                width: 300,
                height: 400,
                collapsible: true,
                maximizable: true,
                resizable: true,
                modal: true,
                buttons: [{
                    text: 'Ok',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //提交表单
                        //调用子窗口的方法.
                        var childWindow = $("#setActionFrame")[0].contentWindow;//表示获取了嵌入在iframe中的子窗体的window对象。
                        childWindow.subForm();//调用子窗体中的方法，完成表单的提交。
                    }
                }, {
                    text: 'Cancel',
                    handler: function () {
                        $('#setActionDiv').dialog('close');
                    }
                }]
            });
        }
        function addInfo() {
            $('#addDiv').css("display", "block");
            $("#addFrame").attr("src", "/RoleInfo/ShowAddInfo");
            $('#addDiv').dialog({
                title: '添加角色数据',
                width: 400,
                height: 400,
                collapsible: true,
                maximizable: true,
                resizable: true,
                modal: true,
                buttons: [{
                    text: 'Ok',
                    iconCls: 'icon-ok',
                    handler: function () {
                        //提交表单
                        //调用子窗口的方法.
                        var childWindow = $("#addFrame")[0].contentWindow;//表示获取了嵌入在iframe中的子窗体的window对象。
                        childWindow.subForm();//调用子窗体中的方法，完成表单的提交。
                    }
                }, {
                    text: 'Cancel',
                    handler: function () {
                        $('#addDiv').dialog('close');
                    }
                }]
            });
        }
        function afterAdd(data) {
            if (data == 'ok') {
                $('#addDiv').dialog('close');
                $("#tt").datagrid('reload');
            } else {
                $.messager.alert("提示", "添加记录失败！", "error");
            }
        }
        //为角色分配完成权限后调用该方法
        function afterSet(data) {
            if (data == "ok") {
                $('#setActionDiv').dialog('close');
                $.messager.alert("提示", "添加权限成功！", "info");
            }
        }
    </script>
</head>
<body>
    <div>
        <div style="margin-top:10px;">
            <table id="tt" style="width: 700px;" title="标题，可以使用代码进行初始化，也可以使用这种属性的方式" iconcls="icon-edit"></table>
        </div>
        <div id="addDiv">
            <iframe id="addFrame" width="100%" height="100%" frameborder="0"></iframe>
        </div>
        <div id="setActionDiv">
            <iframe id="setActionFrame" width="100%" height="100%" frameborder="0"></iframe>
        </div>
    </div>
</body>
</html>

WJQ.OA.WebApp/Views/RoleInfo/ShowAddInfo.cshtml
@model WJQ.OA.Model.RoleInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <title>ShowAddInfo</title>
    <script type="text/javascript">
        $(function () {
            
        });
        function subForm() {
            $('#addForm').submit();
        }
        function afterAdd(data) {
            window.parent.afterAdd(data);
        }
    </script>
</head>
<body>
    @using (Ajax.BeginForm("AddRoleInfo","RoleInfo", new AjaxOptions {HttpMethod="post",OnSuccess="afterAdd" },new {id="addForm" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h4>RoleInfo</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.RoleName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.RoleName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.RoleName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Remark, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Remark, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Remark, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Sort, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Sort, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Sort, "", new { @class = "text-danger" })
                </div>
            </div>    
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

WJQ.OA.WebApp/Views/RoleInfo/ShowRoleAction.cshtml
@{
    Layout = null;
}
@using WJQ.OA.Model
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>为角色分配权限</title>
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
    <script type="text/javascript">
        function subForm() {
            $("#setRoleActionForm").submit();
        }
        function afterSet(data) {
            window.parent.afterSet(data);
        }
    </script>
</head>
<body>
    <div>
        为 @{
            RoleInfo roleInfo = ViewBag.RoleInfo;
            <span style="font-size:14px;color:red;font-weight:bold">@roleInfo.RoleName</span>
        }角色分配权限
        <br />
        @{
            using (Ajax.BeginForm("SetRoleAction", "RoleInfo", new { }, new AjaxOptions() { HttpMethod = "post", OnSuccess = "afterSet" }, new { id = "setRoleActionForm" }))
            {
                <input type="hidden" name="roleId" value="@roleInfo.ID" />
                List<ActionInfo> actionInfoList = ViewBag.ActionInfoList;
                List<int> actionIdList = ViewBag.ActionIdList;
                foreach (var actionInfo in actionInfoList)
                {
                    var actionName = "cba_" + actionInfo.ID;
                    if (actionIdList.Contains(actionInfo.ID))
                    {
                        <input type="checkbox" value="@actionInfo.ID" name="@actionName" checked="checked" />@actionInfo.ActionInfoName
                    }
                    else
                    {
                        <input type="checkbox" value="@actionInfo.ID" name="@actionName" />@actionInfo.ActionInfoName
                    }

                }
            }
        }
    </div>
</body>
</html>